name: AI Code Review

on:
  pull_request:
    paths:
      - '**/*.kt'  # Kotlin 파일에 대해 실행

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드와 submodule 체크아웃
      - name: Checkout code including submodules
        uses: actions/checkout@v3  # 리포지토리 코드 체크아웃
        with:
          submodules: 'true'  # submodule 포함하여 체크아웃
          token: ${{ secrets.ACCOUNT_TOKEN }}  # GitHub Token을 사용하여 인증 처리

      # 2. AI 기반 PR 리뷰어 실행
      - name: AI PR Review and Summary
        uses: coderabbitai/ai-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.ACCOUNT_TOKEN }}  # GitHub 인증을 위한 토큰
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # OpenAI API 키
        with:
          debug: true  # 디버그 정보 출력
          language: ko-KR  # 언어 설정: 한국어
          max_files: 20  # 최대 20개의 파일만 리뷰
          openai_heavy_model: gpt-4o-mini  # 최신 무료 모델 (gpt-3.5-turbo)
          openai_light_model: gpt-4o-mini  # 최신 무료 모델 (gpt-3.5-turbo)
          prompt: "Please review the following Kotlin code and provide suggestions for improvements. Provide your review in Korean:\n\n"  # 프롬프트 명시

      # 3. 디버깅을 위한 마지막 단계
      - name: 디버깅 정보 출력 (필요한 경우)
        if: ${{ !cancelled() }}
        uses: hmarr/debug-action@v3
